#!groovy

node {
        parallel 'eleven':{
            node {
                stage('11'){
                    build 'hpcgBuilder-11'
                    archiveArtifacts allowEmptyArchive: true, artifacts: '*.standardOutput, *.errorLog', excludes: null
                }
            }
        }, 'twelve':{
            node {
                stage('12') {
                    build 'hpcgBuilder-12'
                    archiveArtifacts allowEmptyArchive: true, artifacts: '*.standardOutput, *.errorLog', excludes: null
                }
            }
        }, 'thirteen':{
            node {
                stage('13') {
                    build 'hpcgBuilder-13'
                    archiveArtifacts allowEmptyArchive: true, artifacts: '*.standardOutput, *.errorLog', excludes: null
                }
            }
        }, 'fourteen':{
            node {
                stage('14'){
                    build 'hpcgBuilder-14'
                    archiveArtifacts allowEmptyArchive: true, artifacts: '*.standardOutput, *.errorLog', excludes: null
                }
            }
        }, 'fifteen':{
            node {
                stage('15'){
                    build 'hpcgBuilder-15'
                    archiveArtifacts allowEmptyArchive: true, artifacts: '*.standardOutput, *.errorLog', excludes: null
                }
            }
        }, 'sixteen':{
            node {
                stage('16'){
                    build 'hpcgBuilder-16'
                    archiveArtifacts allowEmptyArchive: true, artifacts: '*.standardOutput, *.errorLog', excludes: null
                }
            }
        }
}