node {

    build 'HPL/hpl11-CopiedJobs/hpl-11copy'


        parallel 'eleven':{
            node {
                stage('11'){
                    build ' HPL/hpl11-CopiedJobs/hpl11Copied'
                    archiveArtifacts allowEmptyArchive: true, artifacts: '*.standardOutput, *.errorLog', excludes: null
                }
            }
        }, 'twelve':{
            node {
                stage('12') {
                    build ' HPL/hpl11-CopiedJobs/hpl12Copied'
                    archiveArtifacts allowEmptyArchive: true, artifacts: '*.standardOutput, *.errorLog', excludes: null
                }
            }
        }, 'thirteen':{
            node {
                stage('13') {
                    build ' HPL/hpl11-CopiedJobs/hpl13Copied'
                    archiveArtifacts allowEmptyArchive: true, artifacts: '*.standardOutput, *.errorLog', excludes: null
                }
            }
        }, 'fourteen':{
            node {
                stage('14'){
                    build ' HPL/hpl11-CopiedJobs/hpl14Copied'
                    archiveArtifacts allowEmptyArchive: true, artifacts: '*.standardOutput, *.errorLog', excludes: null
                }
            }
        }, 'fifteen':{
            node {
                stage('15'){
                    build ' HPL/hpl11-CopiedJobs/hpl15Copied'
                    archiveArtifacts allowEmptyArchive: true, artifacts: '*.standardOutput, *.errorLog', excludes: null
                }
            }
        }, 'sixteen':{
            node {
                stage('16'){
                    build ' HPL/hpl11-CopiedJobs/hpl16Copied'
                    archiveArtifacts allowEmptyArchive: true, artifacts: '*.standardOutput, *.errorLog', excludes: null
                }
            }
        }
}